use std::collections::HashMap;
use std::io::{Read, Write};
use std::path::PathBuf;
use std::sync::Mutex;
use std::thread;

use base64::engine::general_purpose::STANDARD as B64;
use base64::Engine;
use portable_pty::{native_pty_system, Child, CommandBuilder, MasterPty, PtySize};
use tauri::{AppHandle, Emitter};

pub struct PtyHandle {
    master: Box<dyn MasterPty + Send>,
    writer: Box<dyn Write + Send>,
    child: Box<dyn Child + Send + Sync>,
}

#[derive(Default)]
pub struct PtyState(pub Mutex<HashMap<String, PtyHandle>>);

/// Folder each tab's shell started in, for plugin programs to work in.
static TAB_CWD: Mutex<Option<HashMap<String, String>>> = Mutex::new(None);

pub fn tab_cwd(id: &str) -> Option<String> {
    TAB_CWD.lock().unwrap().as_ref()?.get(id).cloned()
}

#[derive(Clone, serde::Serialize)]
struct PtyData {
    id: String,
    /// Raw bytes, base64-encoded so multibyte sequences survive chunk boundaries.
    data: String,
}

#[derive(Clone, serde::Serialize)]
struct PtyExit {
    id: String,
}

/// The shell each tab runs: the user's login shell on Unix, PowerShell on Windows.
fn shell_command() -> CommandBuilder {
    if cfg!(windows) {
        let mut cmd = CommandBuilder::new("powershell.exe");
        cmd.arg("-NoLogo");
        return cmd;
    }
    let shell = std::env::var("SHELL").unwrap_or_else(|_| "/bin/zsh".into());
    let mut cmd = CommandBuilder::new(&shell);
    cmd.arg("-l");
    cmd
}

/// Path of the `claude` shim, single-quoted for a POSIX shell.
#[cfg(not(windows))]
fn quoted_shim() -> Option<String> {
    let shim = crate::hooks::shim_dir()?.join("claude");
    Some(format!(
        "'{}'",
        shim.to_string_lossy().replace('\'', "'\\''")
    ))
}

/// True when the tab's shell is zsh, which gets `claude` from its startup
/// files instead of a typed line.
#[cfg(not(windows))]
fn is_zsh(cmd: &CommandBuilder) -> bool {
    cmd.get_argv()
        .first()
        .and_then(|a| std::path::Path::new(a).file_name().map(|n| n == "zsh"))
        .unwrap_or(false)
}

/// The app's .zshenv, calling the shim at `shim` (already quoted).
#[cfg(not(windows))]
fn zshenv_script(shim: &str) -> String {
    format!(
        "# Generated by Shellhive. Hands the startup files back to the user's\n\
         # folder and defines `claude` once they have all run.\n\
         if [[ -n \"${{SHELLHIVE_ZDOTDIR+x}}\" ]]; then\n\
         \x20 ZDOTDIR=$SHELLHIVE_ZDOTDIR\n\
         \x20 unset SHELLHIVE_ZDOTDIR\n\
         else\n\
         \x20 unset ZDOTDIR\n\
         fi\n\
         _shellhive_resume=${{SHELLHIVE_RESUME-}}\n\
         _shellhive_start=${{SHELLHIVE_START-}}\n\
         unset SHELLHIVE_RESUME SHELLHIVE_START\n\
         [[ -r \"${{ZDOTDIR:-$HOME}}/.zshenv\" ]] && source \"${{ZDOTDIR:-$HOME}}/.zshenv\"\n\
         # Runs the session to reopen, or a new one with a first prompt, as if\n\
         # typed at the first prompt.\n\
         _shellhive_resume_line() {{\n\
         \x20 add-zle-hook-widget -d line-init _shellhive_resume_line\n\
         \x20 if [[ -n \"$_shellhive_resume\" ]]; then\n\
         \x20   BUFFER=\"claude --resume $_shellhive_resume\"\n\
         \x20 else\n\
         \x20   BUFFER=\"claude ${{(q)_shellhive_start}}\"\n\
         \x20 fi\n\
         \x20 unset _shellhive_resume _shellhive_start\n\
         \x20 zle accept-line\n\
         }}\n\
         _shellhive_init() {{\n\
         \x20 claude() {{ {shim} \"$@\"; }}\n\
         \x20 precmd_functions=(${{precmd_functions:#_shellhive_init}})\n\
         \x20 unfunction _shellhive_init\n\
         \x20 if [[ -n \"$_shellhive_resume$_shellhive_start\" ]]; then\n\
         \x20   autoload -Uz add-zle-hook-widget\n\
         \x20   add-zle-hook-widget line-init _shellhive_resume_line\n\
         \x20 fi\n\
         }}\n\
         [[ -o interactive ]] && precmd_functions+=(_shellhive_init)\n"
    )
}

/// Points zsh at a startup folder of the app's own. Its .zshenv hands every
/// other startup file back to the user's folder, and defines `claude` right
/// before the first prompt, after the user's files have all run. A line typed
/// while those files load can be swallowed by one that reads input (the
/// oh-my-zsh update question does), and `claude` would then miss the app's
/// settings.
#[cfg(not(windows))]
fn zsh_integration(cmd: &mut CommandBuilder) -> Result<(), String> {
    let dir = crate::paths::data_dir().ok_or("no config dir")?.join("zsh");
    std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    let shim = quoted_shim().ok_or("no config dir")?;
    std::fs::write(dir.join(".zshenv"), zshenv_script(&shim)).map_err(|e| e.to_string())?;
    if let Some(original) = std::env::var_os("ZDOTDIR") {
        cmd.env("SHELLHIVE_ZDOTDIR", original);
    }
    cmd.env("ZDOTDIR", &dir);
    Ok(())
}

/// Session ids are UUIDs; anything else could smuggle shell syntax in.
fn valid_session(session: &str) -> bool {
    !session.is_empty()
        && session
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-')
}

/// Line typed into a new tab to reopen a Claude session. It calls the shim by
/// path, so the session gets the app's settings even if `claude` was not
/// defined in time.
fn resume_line(session: &str) -> Option<String> {
    #[cfg(windows)]
    {
        Some(format!("claude --resume {session}\r"))
    }
    #[cfg(not(windows))]
    {
        Some(format!("{} --resume {session}\n", quoted_shim()?))
    }
}

/// Line typed into a new tab to start Claude with the first prompt in
/// SHELLHIVE_START, read by the shell from the environment.
fn start_line() -> Option<String> {
    #[cfg(windows)]
    {
        Some("claude $env:SHELLHIVE_START\r".to_string())
    }
    #[cfg(not(windows))]
    {
        Some(format!("{} \"$SHELLHIVE_START\"\n", quoted_shim()?))
    }
}

/// Line typed into a new tab so every `claude` there carries the app's
/// settings and a per-tab MCP config. On Unix it points at the shim; on
/// Windows it is a PowerShell function doing the same thing, since there is
/// no shim script to run there.
fn claude_function() -> Option<String> {
    #[cfg(windows)]
    {
        let settings = crate::hooks::settings_path()?;
        let settings = settings.to_string_lossy().replace('\'', "''");
        let port = crate::hooks::PORT;
        Some(format!(
            "function claude {{ $t = $env:SHELLHIVE_TAB_ID; \
             $m = Join-Path $env:TEMP \"shellhive-mcp-$t.json\"; \
             '{{\"mcpServers\":{{\"shellhive\":{{\"type\":\"http\",\"url\":\"http://127.0.0.1:{port}/mcp\",\"headers\":{{\"X-Tab-Id\":\"' + $t + '\"}}}}}}}}' | Set-Content -Encoding ascii $m; \
             $real = (Get-Command claude -CommandType Application -ErrorAction SilentlyContinue | Select-Object -First 1).Source; \
             if (-not $real) {{ Write-Error 'claude nao encontrado no PATH'; return }}; \
             & $real --settings '{settings}' --mcp-config $m @args }}; Clear-Host\r"
        ))
    }
    #[cfg(not(windows))]
    {
        Some(format!(
            "claude() {{ {} \"$@\"; }}; hash -r 2>/dev/null; clear\n",
            quoted_shim()?
        ))
    }
}

// A Tauri command takes its arguments as parameters, one per field the
// interface sends.
#[allow(clippy::too_many_arguments)]
#[tauri::command]
pub fn pty_spawn(
    app: AppHandle,
    state: tauri::State<PtyState>,
    id: String,
    cols: u16,
    rows: u16,
    cwd: Option<String>,
    resume: Option<String>,
    prompt: Option<String>,
) -> Result<(), String> {
    if state.0.lock().unwrap().contains_key(&id) {
        return Ok(());
    }

    let pair = native_pty_system()
        .openpty(PtySize {
            rows,
            cols,
            pixel_width: 0,
            pixel_height: 0,
        })
        .map_err(|e| e.to_string())?;

    let mut cmd = shell_command();

    // If the app itself was launched from inside a Claude Code session, its
    // session markers leak into every tab. A `claude` started here would then
    // consider itself a child session and stop saving transcripts, which the
    // session list and resume depend on. Drop them so each tab is top level.
    let mut scrubbed: Vec<String> = Vec::new();
    for (key, _) in std::env::vars() {
        let leaked = key.starts_with("CLAUDE_CODE_")
            || matches!(key.as_str(), "CLAUDECODE" | "CLAUDE_PID" | "CLAUDE_EFFORT");
        if leaked {
            cmd.env_remove(&key);
            scrubbed.push(key);
        }
    }
    if !scrubbed.is_empty() {
        eprintln!(
            "[pty] scrubbed inherited Claude Code vars: {}",
            scrubbed.join(", ")
        );
    }

    // Put the `claude` shim ahead of the real binary for this shell.
    if let Some(bin) = crate::hooks::shim_dir() {
        let current = std::env::var_os("PATH").unwrap_or_default();
        let paths = std::iter::once(bin).chain(std::env::split_paths(&current));
        if let Ok(joined) = std::env::join_paths(paths) {
            cmd.env("PATH", joined);
        }
    }

    cmd.env("TERM", "xterm-256color");
    cmd.env("COLORTERM", "truecolor");
    // Programs that detect hyperlink support (Claude Code included) then print
    // file paths and URLs as OSC 8 links, which the terminal makes clickable.
    cmd.env("FORCE_HYPERLINK", "1");
    cmd.env("SHELLHIVE_TAB_ID", &id);
    #[cfg(not(windows))]
    let zsh_ready = is_zsh(&cmd)
        && zsh_integration(&mut cmd)
            .map_err(|e| crate::errors::record("pty", &format!("zsh integration: {e}")))
            .is_ok();
    #[cfg(windows)]
    let zsh_ready = false;
    let resume = resume.filter(|s| valid_session(s));
    // A first prompt for a new session; resuming one takes precedence. It
    // travels in the environment, so the shell never parses it as code.
    let prompt = prompt.filter(|p| resume.is_none() && !p.trim().is_empty());
    if let Some(text) = &prompt {
        cmd.env("SHELLHIVE_START", text);
    }
    // zsh reopens the session from its startup files, where no startup file
    // can swallow the command.
    if zsh_ready {
        if let Some(session) = &resume {
            cmd.env("SHELLHIVE_RESUME", session);
        }
    }
    if let Some(dir) = cwd.map(PathBuf::from).or_else(dirs::home_dir) {
        TAB_CWD
            .lock()
            .unwrap()
            .get_or_insert_with(HashMap::new)
            .insert(id.clone(), dir.to_string_lossy().to_string());
        cmd.cwd(dir);
    }

    let child = pair.slave.spawn_command(cmd).map_err(|e| e.to_string())?;
    drop(pair.slave);

    let mut reader = pair.master.try_clone_reader().map_err(|e| e.to_string())?;
    let mut writer = pair.master.take_writer().map_err(|e| e.to_string())?;

    // A PATH entry alone is not enough: the shell's startup files can reorder
    // PATH and zsh caches command lookups. A function is resolved before both,
    // so every `claude` typed in this tab reaches the shim. zsh already gets
    // it from its startup files.
    let (init, resume, start) = if zsh_ready {
        (None, None, None)
    } else {
        (claude_function(), resume, prompt.and_then(|_| start_line()))
    };
    let lines = init
        .into_iter()
        .chain(resume.as_deref().and_then(resume_line))
        .chain(start);
    for line in lines {
        let _ = writer.write_all(line.as_bytes());
    }
    let _ = writer.flush();

    let reader_app = app.clone();
    let reader_id = id.clone();
    thread::spawn(move || {
        let mut buf = [0u8; 8192];
        loop {
            match reader.read(&mut buf) {
                Ok(0) | Err(_) => break,
                Ok(n) => {
                    let _ = reader_app.emit(
                        "pty-data",
                        PtyData {
                            id: reader_id.clone(),
                            data: B64.encode(&buf[..n]),
                        },
                    );
                }
            }
        }
        let _ = reader_app.emit("pty-exit", PtyExit { id: reader_id });
    });

    state.0.lock().unwrap().insert(
        id,
        PtyHandle {
            master: pair.master,
            writer,
            child,
        },
    );
    Ok(())
}

#[tauri::command]
pub fn pty_write(state: tauri::State<PtyState>, id: String, data: String) -> Result<(), String> {
    let mut map = state.0.lock().unwrap();
    let handle = map.get_mut(&id).ok_or("pty not found")?;
    handle
        .writer
        .write_all(data.as_bytes())
        .map_err(|e| e.to_string())?;
    handle.writer.flush().map_err(|e| e.to_string())
}

#[tauri::command]
pub fn pty_resize(
    state: tauri::State<PtyState>,
    id: String,
    cols: u16,
    rows: u16,
) -> Result<(), String> {
    let map = state.0.lock().unwrap();
    let handle = map.get(&id).ok_or("pty not found")?;
    handle
        .master
        .resize(PtySize {
            rows,
            cols,
            pixel_width: 0,
            pixel_height: 0,
        })
        .map_err(|e| e.to_string())
}

#[tauri::command]
pub fn pty_kill(state: tauri::State<PtyState>, id: String) -> Result<(), String> {
    let mut map = state.0.lock().unwrap();
    if let Some(mut handle) = map.remove(&id) {
        let _ = handle.child.kill();
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::valid_session;
    #[cfg(not(windows))]
    use super::zshenv_script;

    #[test]
    fn accepts_only_session_ids() {
        assert!(valid_session("2627d6a7-32ec-4632-b750-011174b0ba4d"));
        assert!(!valid_session(""));
        assert!(!valid_session("x; rm -rf ~"));
        assert!(!valid_session("$(id)"));
    }

    /// The first prompt reaches zsh only through ${(q)...}, which quotes it
    /// as a single word, so it can never run as code.
    #[cfg(not(windows))]
    #[test]
    fn the_first_prompt_is_quoted_by_zsh() {
        let script = zshenv_script("'/shim'");
        assert!(script.contains("BUFFER=\"claude ${(q)_shellhive_start}\""));
        assert!(script.contains("unset SHELLHIVE_RESUME SHELLHIVE_START"));
    }
}
